name: pre-commit-checks
description: Run pre-commit checks

on:
    workflow_call:

jobs:
    using: composite
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.3.2

      - name: Install python or load from cache with dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install --all-extras --with dev

      - name: Run pre-commit checks
        run: |
          poetry run pre-commit run --all-files
