name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install "poetry==1.3.2" && poetry install --all-extras --with dev

      - name: Run unit tests
        run: |
          make test_not_vespa

      - name: Install latest Vespa CLI
        env:
          VESPA_CLI_VERSION: "8.250.43"
        run: |
          mkdir vespa-cli
          curl -fsSL https://github.com/vespa-engine/vespa/releases/download/v${VESPA_CLI_VERSION}/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64.tar.gz | \
            tar -zxf - -C vespa-cli --strip-component=1
          echo "vespa-cli/bin" >> $GITHUB_PATH

      - name: Setup vespa test instance
        run: make vespa_dev_setup
  
      - name: Run vespa tests
        run: |
          make test
